[package]
name = "optlevel-z-crt-static-issue"
version = "0.1.0"
authors = ["oblique <psyberbits@gmail.com>"]
edition = "2018"

[dependencies]
zmq = { version = "0.9.2", features = ["vendored"] }

[profile.release]
opt-level = "z"
