[package]
name = "optlevel-z-crt-static-issue"
version = "0.1.0"
authors = ["oblique <psyberbits@gmail.com>"]
edition = "2018"

[build-dependencies]
zeromq-src = "0.1.8"

[profile.release]
opt-level = "z"
