name: Build
on: [push]

jobs:
    build:
        name: Build
        runs-on: windows-latest
        steps:
            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
            - name: Checkout sources
              uses: actions/checkout@v1
            - name: Build
              shell: pwsh
              run: |
                  $Env:RUSTFLAGS = "-Ctarget-feature=+crt-static"
                  cargo build --release
